// <auto-generated />
namespace Nishkriya.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class PrepareForMultiForum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PrepareForMultiForum));
        
        string IMigrationMetadata.Id
        {
            get { return "201311031932320_PrepareForMultiForum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
