// <auto-generated />
namespace Nishkriya.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserEmailAdminMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserEmailAdminMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201301222148286_IsAdmin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
