// <auto-generated />
namespace Nishkriya.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ScrapeStatistics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScrapeStatistics));
        
        string IMigrationMetadata.Id
        {
            get { return "201301241952580_ScrapeStatistics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
